const countries = {
  'hi-IN':'Hindi',
  'en-US':'English',
  'es-ES': 'Spanish', 
  'fr-FR': 'French', 
  'de-DE': 'German',
  'ja-JP': 'Japanese',
  'zh-CN': 'Chinese', 
  'ko-KR': 'Korean', 
  'pt-BR': 'Portuguese' ,
  'pt-PT': 'Portugueseal' ,
  'it-IT': 'Italian', 
  'ru-RU': 'Russian', 
  'ar-SA': 'Arabic', 
  'hi-IN': 'Hindi', 
  'tr-TR': 'Turkish', 
  'nl-NL': 'Dutch', 
  'pl-PL': 'Polish', 
  'sv-SE': 'Swedish', 
  'th-TH': 'Thai', 
  'el-GR': 'Greek', 
  'id-ID': 'Indonesiansia',
  'vi-VN': 'Vietnamesem' ,
  'da-DK': 'Danish', 
  'fi-FI': 'Finnish',
  'no-NO': 'Norwegian' ,
  'uk-UA': 'Ukrainian',
};